### ISSUE TITLE
Misleading notification while creating environment

### ISSUE THREAD

**Issue by karrtikr** [brettcannon/WWBD#20] opened 2022-05-02 23:42 UTC
Issue Type: <b>Bug</b>

This maybe a dup of https://github.com/brettcannon/WWBD/issues/17.

- Select a non-global interpreter
- See prompt asking to select a global interpreter, select one.
- Still see the following notification while environment is being created:
![image](https://user-images.githubusercontent.com/13199757/166343199-eda646cd-1b6e-43ad-b047-ff3b14a8a865.png)

Extension version: 2022.0.1
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22518
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.80GB free)|
|Process Argv|--crash-reporter-id ba85916b-757f-4637-bf70-2eefba6645b4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by brettcannon** [comment] 2022-05-03 00:21
Duplicate of #17

**Closed by brettcannon** 2022-05-03 00:21 UTC
